spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: automechanics
  datasource:
    url: jdbc:postgresql://localhost:6000/automechanics
    username: postgres
    password: postgres
    name: automechanics
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
        - src/main/java/
